apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana
  namespace: default
  labels:
    component: elasticsearch
    role: kibana
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: kibana
  template:
    metadata:
      labels:
        component: elasticsearch
        role: kibana
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: kibana
        image: bobrik/kibana
        env:
        -name: KIBANA_ES_URL
         value: "http://elasticsearch:9200"
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP